export const houses = [
  {
    id: 1,
    price: 1500,
    category: 'duplex',
    location: 'Maseru',
    status: 'available',
    place: 'Ha Tsolo',
    landlord: 45,
    image: require('../assets/houses/1.jpeg'),
    description:
      ' It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It wa popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
    rating: 7,
    requesters: [],
  },
  {
    id: 2,
    price: 4500,
    category: 'duplex',
    location: 'Leribe',
    place: 'Maputsoe',
    status: 'available',
    landlord: 45,
    image: require('../assets/houses/house.jpeg'),
    description:
      ' It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It wa popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
    rating: 0,
    requesters: [],
  },
  {
    id: 3,
    price: 1500,
    category: 'duplex',
    location: 'Maseru',
    place: 'Masowe 2',
    status: 'available',
    landlord: 45,
    image: require('../assets/houses/2.jpeg'),
    description:
      ' It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It wa popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
    rating: 54,
    requesters: [],
  },
  {
    id: 4,
    price: 15100,
    category: 'duplex',
    location: 'Berea',
    place: 'Ty',
    status: 'available',
    landlord: 45,
    image: require('../assets/houses/house.jpeg'),
    description:
      ' It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It wa popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
    rating: 44,
    requesters: [],
  },
  {
    id: 5,
    price: 400,
    category: 'single',
    location: 'Berea',
    place: 'Ntjabane',
    status: 'available',
    landlord: 45,
    image: require('../assets/houses/house.jpeg'),
    description:
      ' It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It wa popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
    rating: 4,
    requesters: [],
  },
  {
    id: 6,
    price: 400,
    category: 'single',
    location: 'Mafeteng',
    place: 'Toropong',
    status: 'available',
    landlord: 45,
    image: require('../assets/houses/house.jpeg'),
    description:
      ' It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It wa popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
    rating: 4,
    requesters: [],
  },
  {
    id: 7,
    price: 600,
    category: 'double',
    location: 'Maseru',
    place: 'Ratjomose',
    status: 'available',
    landlord: 45,
    image: require('../assets/houses/house.jpeg'),
    description:
      ' It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It wa popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
    rating: 4,
    requesters: [],
  },
  {
    id: 8,
    price: 1200,
    category: 'hotel',
    location: 'Maseru',
    place: 'Town',
    status: 'available',
    landlord: 45,
    image: require('../assets/houses/house.jpeg'),
    description:
      ' It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It wa popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
    rating: 8,
    requesters: [],
  },
  {
    id: 9,
    price: 500,
    category: 'single',
    location: 'Maseru',
    place: 'Qoaling',
    status: 'available',
    landlord: 45,
    image: require('../assets/houses/house.jpeg'),
    description:
      ' It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It wa popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
    rating: 7,
    requesters: [],
  },
];
